apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system-container
        image: toqaabdalla/solar-system:v1.0
        env:
          - name: MONGO_URI
            valueFrom: 
              configMapKeyRef:
                name: solar-cm
                key: MONGO_URI
          - name: MONGO_USERNAME
            valueFrom: 
              secretKeyRef:
                name: solar-secret
                key: MONGO_USERNAME
          - name: MONGO_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: solar-secret
                key: MONGO_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
